sender: sender.cpp
	g++ -I ../src -std=c++11 sender.cpp ../src/util.cpp ../src/packet.cpp ../src/logging.cpp -lpthread -o sender
receiver: receiver.cpp
	g++ -I ../src -std=c++11 receiver.cpp ../src/util.cpp ../src/logging.cpp -lpthread -o receiver
